#!/usr/bin/env bash

@class MouseDriver

    function MouseDriver.enableMouseButtonsCapture()
    {
        echo -e "\e[?1000h"
        echo -e "\e[?9h"

        $this.subscribeToShutdown
    }

    function MouseDriver.enableMouseDragCapture()
    {
        echo -e "\e[?1002h"

        $this.subscribeToShutdown
    }

    function MouseDriver.enableMouseMovementCapture()
    {
        echo -e "\e[?1003h"

        $this.subscribeToShutdown
    }

    function MouseDriver.disableMouseCapture()
    {
        echo -e "\e[?1000l"
        echo -e "\e[?1002l"
        echo -e "\e[?1003l"
        echo -e "\e[?9l"
    }

    function MouseDriver.updateMouseStatus()
    {
        local input="${1}"
        local target="${2}"

        @let buttonStatus = $this.chrToInt "${input:3:1}"
        @let $target.mouseX = $this.chrToInt "${input:4:1}"
        @let $target.mouseY = $this.chrToInt "${input:5:1}"

        case ${buttonStatus} in
          0)
              $target.mouseButtonLeft = true
              $target.mouseButtonRight = false
            ;;
          1)
              $target.mouseButtonLeft = false
              $target.mouseButtonRight = true
            ;;
          2)
              $target.mouseButtonLeft = false
              $target.mouseButtonRight = false
            ;;
        esac
    }

    function MouseDriver.subscribeToShutdown()
    {
        besharp.addShutdownCallback 'mouse_disable_capture' $this.disableMouseCapture
    }

    function MouseDriver.chrToInt()
    {
        # generated by:
        #  for i in $(seq 33 255); do
        #      echo "          $'\x$( printf '%x\n' "${i}" )') @returning "$(( i - 33 ))" ;;"
        #  done
        case "${1}" in
          $'\x21') @returning 0 ;;
          $'\x22') @returning 1 ;;
          $'\x23') @returning 2 ;;
          $'\x24') @returning 3 ;;
          $'\x25') @returning 4 ;;
          $'\x26') @returning 5 ;;
          $'\x27') @returning 6 ;;
          $'\x28') @returning 7 ;;
          $'\x29') @returning 8 ;;
          $'\x2a') @returning 9 ;;
          $'\x2b') @returning 10 ;;
          $'\x2c') @returning 11 ;;
          $'\x2d') @returning 12 ;;
          $'\x2e') @returning 13 ;;
          $'\x2f') @returning 14 ;;
          $'\x30') @returning 15 ;;
          $'\x31') @returning 16 ;;
          $'\x32') @returning 17 ;;
          $'\x33') @returning 18 ;;
          $'\x34') @returning 19 ;;
          $'\x35') @returning 20 ;;
          $'\x36') @returning 21 ;;
          $'\x37') @returning 22 ;;
          $'\x38') @returning 23 ;;
          $'\x39') @returning 24 ;;
          $'\x3a') @returning 25 ;;
          $'\x3b') @returning 26 ;;
          $'\x3c') @returning 27 ;;
          $'\x3d') @returning 28 ;;
          $'\x3e') @returning 29 ;;
          $'\x3f') @returning 30 ;;
          $'\x40') @returning 31 ;;
          $'\x41') @returning 32 ;;
          $'\x42') @returning 33 ;;
          $'\x43') @returning 34 ;;
          $'\x44') @returning 35 ;;
          $'\x45') @returning 36 ;;
          $'\x46') @returning 37 ;;
          $'\x47') @returning 38 ;;
          $'\x48') @returning 39 ;;
          $'\x49') @returning 40 ;;
          $'\x4a') @returning 41 ;;
          $'\x4b') @returning 42 ;;
          $'\x4c') @returning 43 ;;
          $'\x4d') @returning 44 ;;
          $'\x4e') @returning 45 ;;
          $'\x4f') @returning 46 ;;
          $'\x50') @returning 47 ;;
          $'\x51') @returning 48 ;;
          $'\x52') @returning 49 ;;
          $'\x53') @returning 50 ;;
          $'\x54') @returning 51 ;;
          $'\x55') @returning 52 ;;
          $'\x56') @returning 53 ;;
          $'\x57') @returning 54 ;;
          $'\x58') @returning 55 ;;
          $'\x59') @returning 56 ;;
          $'\x5a') @returning 57 ;;
          $'\x5b') @returning 58 ;;
          $'\x5c') @returning 59 ;;
          $'\x5d') @returning 60 ;;
          $'\x5e') @returning 61 ;;
          $'\x5f') @returning 62 ;;
          $'\x60') @returning 63 ;;
          $'\x61') @returning 64 ;;
          $'\x62') @returning 65 ;;
          $'\x63') @returning 66 ;;
          $'\x64') @returning 67 ;;
          $'\x65') @returning 68 ;;
          $'\x66') @returning 69 ;;
          $'\x67') @returning 70 ;;
          $'\x68') @returning 71 ;;
          $'\x69') @returning 72 ;;
          $'\x6a') @returning 73 ;;
          $'\x6b') @returning 74 ;;
          $'\x6c') @returning 75 ;;
          $'\x6d') @returning 76 ;;
          $'\x6e') @returning 77 ;;
          $'\x6f') @returning 78 ;;
          $'\x70') @returning 79 ;;
          $'\x71') @returning 80 ;;
          $'\x72') @returning 81 ;;
          $'\x73') @returning 82 ;;
          $'\x74') @returning 83 ;;
          $'\x75') @returning 84 ;;
          $'\x76') @returning 85 ;;
          $'\x77') @returning 86 ;;
          $'\x78') @returning 87 ;;
          $'\x79') @returning 88 ;;
          $'\x7a') @returning 89 ;;
          $'\x7b') @returning 90 ;;
          $'\x7c') @returning 91 ;;
          $'\x7d') @returning 92 ;;
          $'\x7e') @returning 93 ;;
          $'\x7f') @returning 94 ;;
          $'\x80') @returning 95 ;;
          $'\x81') @returning 96 ;;
          $'\x82') @returning 97 ;;
          $'\x83') @returning 98 ;;
          $'\x84') @returning 99 ;;
          $'\x85') @returning 100 ;;
          $'\x86') @returning 101 ;;
          $'\x87') @returning 102 ;;
          $'\x88') @returning 103 ;;
          $'\x89') @returning 104 ;;
          $'\x8a') @returning 105 ;;
          $'\x8b') @returning 106 ;;
          $'\x8c') @returning 107 ;;
          $'\x8d') @returning 108 ;;
          $'\x8e') @returning 109 ;;
          $'\x8f') @returning 110 ;;
          $'\x90') @returning 111 ;;
          $'\x91') @returning 112 ;;
          $'\x92') @returning 113 ;;
          $'\x93') @returning 114 ;;
          $'\x94') @returning 115 ;;
          $'\x95') @returning 116 ;;
          $'\x96') @returning 117 ;;
          $'\x97') @returning 118 ;;
          $'\x98') @returning 119 ;;
          $'\x99') @returning 120 ;;
          $'\x9a') @returning 121 ;;
          $'\x9b') @returning 122 ;;
          $'\x9c') @returning 123 ;;
          $'\x9d') @returning 124 ;;
          $'\x9e') @returning 125 ;;
          $'\x9f') @returning 126 ;;
          $'\xa0') @returning 127 ;;
          $'\xa1') @returning 128 ;;
          $'\xa2') @returning 129 ;;
          $'\xa3') @returning 130 ;;
          $'\xa4') @returning 131 ;;
          $'\xa5') @returning 132 ;;
          $'\xa6') @returning 133 ;;
          $'\xa7') @returning 134 ;;
          $'\xa8') @returning 135 ;;
          $'\xa9') @returning 136 ;;
          $'\xaa') @returning 137 ;;
          $'\xab') @returning 138 ;;
          $'\xac') @returning 139 ;;
          $'\xad') @returning 140 ;;
          $'\xae') @returning 141 ;;
          $'\xaf') @returning 142 ;;
          $'\xb0') @returning 143 ;;
          $'\xb1') @returning 144 ;;
          $'\xb2') @returning 145 ;;
          $'\xb3') @returning 146 ;;
          $'\xb4') @returning 147 ;;
          $'\xb5') @returning 148 ;;
          $'\xb6') @returning 149 ;;
          $'\xb7') @returning 150 ;;
          $'\xb8') @returning 151 ;;
          $'\xb9') @returning 152 ;;
          $'\xba') @returning 153 ;;
          $'\xbb') @returning 154 ;;
          $'\xbc') @returning 155 ;;
          $'\xbd') @returning 156 ;;
          $'\xbe') @returning 157 ;;
          $'\xbf') @returning 158 ;;
          $'\xc0') @returning 159 ;;
          $'\xc1') @returning 160 ;;
          $'\xc2') @returning 161 ;;
          $'\xc3') @returning 162 ;;
          $'\xc4') @returning 163 ;;
          $'\xc5') @returning 164 ;;
          $'\xc6') @returning 165 ;;
          $'\xc7') @returning 166 ;;
          $'\xc8') @returning 167 ;;
          $'\xc9') @returning 168 ;;
          $'\xca') @returning 169 ;;
          $'\xcb') @returning 170 ;;
          $'\xcc') @returning 171 ;;
          $'\xcd') @returning 172 ;;
          $'\xce') @returning 173 ;;
          $'\xcf') @returning 174 ;;
          $'\xd0') @returning 175 ;;
          $'\xd1') @returning 176 ;;
          $'\xd2') @returning 177 ;;
          $'\xd3') @returning 178 ;;
          $'\xd4') @returning 179 ;;
          $'\xd5') @returning 180 ;;
          $'\xd6') @returning 181 ;;
          $'\xd7') @returning 182 ;;
          $'\xd8') @returning 183 ;;
          $'\xd9') @returning 184 ;;
          $'\xda') @returning 185 ;;
          $'\xdb') @returning 186 ;;
          $'\xdc') @returning 187 ;;
          $'\xdd') @returning 188 ;;
          $'\xde') @returning 189 ;;
          $'\xdf') @returning 190 ;;
          $'\xe0') @returning 191 ;;
          $'\xe1') @returning 192 ;;
          $'\xe2') @returning 193 ;;
          $'\xe3') @returning 194 ;;
          $'\xe4') @returning 195 ;;
          $'\xe5') @returning 196 ;;
          $'\xe6') @returning 197 ;;
          $'\xe7') @returning 198 ;;
          $'\xe8') @returning 199 ;;
          $'\xe9') @returning 200 ;;
          $'\xea') @returning 201 ;;
          $'\xeb') @returning 202 ;;
          $'\xec') @returning 203 ;;
          $'\xed') @returning 204 ;;
          $'\xee') @returning 205 ;;
          $'\xef') @returning 206 ;;
          $'\xf0') @returning 207 ;;
          $'\xf1') @returning 208 ;;
          $'\xf2') @returning 209 ;;
          $'\xf3') @returning 210 ;;
          $'\xf4') @returning 211 ;;
          $'\xf5') @returning 212 ;;
          $'\xf6') @returning 213 ;;
          $'\xf7') @returning 214 ;;
          $'\xf8') @returning 215 ;;
          $'\xf9') @returning 216 ;;
          $'\xfa') @returning 217 ;;
          $'\xfb') @returning 218 ;;
          $'\xfc') @returning 219 ;;
          $'\xfd') @returning 220 ;;
          $'\xfe') @returning 221 ;;
          $'\xff') @returning 222 ;;
          *) @returning 0;;
        esac
    }

@classdone